---
- name: Install Docker and deploy container on VMware VMs
  hosts: vmware_vms
  become: yes
  vars:
    ansible_ssh_private_key_file: "/home/rayan/.ssh/id_rsa"  # Path to your private key
    docker_image: "rayanelsharkawy/python-app"               # Docker image variable
    docker_username: "{{ lookup('env', 'DOCKER_USERNAME') }}"  # Set as environment variable
    docker_password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"  # Set as environment variable

  tasks:
    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      register: docker_dependencies
      changed_when: docker_dependencies is changed

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker's official APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Install Python Docker SDK
      pip:
        name: docker
        state: present

    - name: Log in to Docker Hub
      docker_login:
        username: "{{ docker_username }}"  # Use environment variable
        password: "{{ docker_password }}"  # Use environment variable

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: "{{ docker_image }}"                         # Reference Docker image variable
        source: pull

    - name: Run Docker container
      docker_container:
        name: python-app
        image: "{{ docker_image }}"                        # Reference Docker image variable
        state: started
        ports:
          - "80:80"
        restart_policy: always                             # Ensure container restarts on failure
